### ISSUE TITLE
How to get public key via Chrome Extension

### ISSUE THREAD

**Issue by sgurin** [PolymathNetwork/polymesh-wallet#241]
Hi.

Is there any documentation on how to interact with Polymesh Wallet Extension from web page?

On my WebPage I need to get wallet ID/Public Key from extension that user has already installed. Smth like web3 global object on metaMask https://docs.metamask.io/guide/ethereum-provider.html#table-of-contents

**Comment by F-OBrien** [comment]
I agree that we could do with some Polymesh specific examples and documentation to help with these kind of things. I've not looked to see if there are Polymesh specific functions for wallet interaction build into the Polymesh SDK but the Polymesh SDK is built on the Polkadot API and as such you can use the Polkadot API functions to inject accounts from the wallet extension.

Have a read of https://polkadot.js.org/docs/extension and also look at https://github.com/PolymathNetwork/mock-uid-provider/blob/master/src/App.tsx which is an example of a dApp interacting with the wallet extension via the Polkadot api (https://polymathnetwork.github.io/mock-uid-provider/)

I've not actually tried to use these features yet so if someone from the Polymath/Polymesh team has more to add maybe specific to an implementation using the Polymesh SDK it would be good.

**Comment by wahidrahim** [comment]
@F-OBrien pointed out a great example. This is perhaps the most barebones example of connecting with the polymesh-wallet and getting the accounts (public keys): https://github.com/PolymathNetwork/mock-uid-provider/blob/master/src/App.tsx#L137-L170

Note that the selected account in the wallet is always at index 0.

**Comment by sgurin** [comment]
Thanks

**Comment by sgurin** [comment]
Hi, guys. Smth strange error happening when I trying to import module 
![image](https://user-images.githubusercontent.com/25930200/151407332-5c2e8b14-cf59-4455-a953-60e02de77cb4.png)
I assume that I need to add WebAssmble loader. Right?

**Comment by wahidrahim** [comment]
Hmm, I'm not familiar with this error, although I am not seeing anything in the screenshot that points to needing wasm loader in particular either.

The mock-uid-provider app is just a simple react app through create-react-app, so there's no need for configuring webpack/loaders.

If it helps, for your reference, here is the webpack config for wallet: https://github.com/PolymathNetwork/polymesh-wallet/blob/develop/packages/extension/webpack.shared.cjs

**Comment by sgurin** [comment]
Thanks, a lot. Now get another error with loader :) 
![image](https://user-images.githubusercontent.com/25930200/151561745-9f3507a9-802f-4617-b066-643745098064.png)

**Comment by sgurin** [comment]
I think Polkadot SDK is not bundled correct. Best practices is use UMD for module and transpile code in ES6. 

In some files I see `_this` that means code was transpiled but at the same time `this.#chainProperties` class private properties not transpiled. I assume that they did not use https://babeljs.io/docs/en/babel-plugin-proposal-private-methods or @babel/preset-env

![image](https://user-images.githubusercontent.com/25930200/151586503-b3809a78-fa5e-44a7-84c7-60f4544c1d6c.png)

**Comment by sgurin** [comment]
Is there any way to check extension support in browser? The example does not process that case and shows errors in console 
![image](https://user-images.githubusercontent.com/25930200/152365143-fcd2bb46-3d02-437d-8bec-a29a7031985d.png)

**Comment by F-OBrien** [comment]
> Is there any way to check extension support in browser? The example does not process that case and shows errors in console ![image](https://user-images.githubusercontent.com/25930200/152365143-fcd2bb46-3d02-437d-8bec-a29a7031985d.png)

Chrome browser extensions aren't supported on the mobile Chrome browser. The only mobile chromium based browser that I've seen to support the Polymesh wallet extension is Kiwi browser.

**Comment by sgurin** [comment]
I think we should provide information for user that browser does not support extension. So, is there any standards on How to Check browser extension support? I have found solution https://stackoverflow.com/questions/60887465/how-to-detect-whether-browser-supports-chrome-extensions but do not like it.

**Comment by wahidrahim** [comment]
Perhaps we can clarify these things through some documentation. There are some that are being prepared right now, we can add this as part of the information as well.

As F-OBrien mentioned, chrome extensions generally do not work in the mobile instances of the chrome browser. We also do not officially have mobile support in general for the polymesh-wallet and dApps that require polymesh-wallet (just yet).

@sgurin if you are able to share some use cases I can check alternative methods for you to possibly accomplish your features. Also, I would love to hear how you solved the integration issue in Vue!

**Comment by sgurin** [comment]
I have only found one solution is to check !window.chrome?.runtime?.sendMessage so if it is not chrome and does not have sendMessage property than extension will not work.

Now I have another problem. If user opens a page with turned off extension and than turned it on. I cannot find any event in the browser that can help me to detecting turning on/off extension proccess.

**Comment by wahidrahim** [comment]
@sgurin as far as I know there isn't an event that allows detecting when an extension is turned on or off, not in a simple way anyway, from the client side. Might just need to refresh the client when the extension is turned on again.
